### ISSUE TITLE
add css support

### ISSUE THREAD

**Issue by cyberhck** [crazyfactory/ts-react-boilerplate#281]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I try to use UI libraries, but then I've to set up CSS/SCSS

**Describe the solution you'd like**
I'd like to have isomorphic css and scss loader because the fact is that we need css at some point anyway, and having css loader, and removing later if not wanted is more easy than not having a css loader and having to add everything when needed.

**Describe alternatives you've considered**
I don't know of any alternatives that we might have.

**Additional context**
I was trying to use ant.design and this happened.

**Comment by paibamboo** [comment]
Since [isormorphic-style-loader](https://github.com/kriasoft/isomorphic-style-loader/) isn't maintained anymore (it even contains its [own React version](https://github.com/kriasoft/isomorphic-style-loader/issues/155)!) and style-loader does not support ssr. I will go with [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) approach by this [suggestion](https://github.com/webpack-contrib/style-loader/pull/159#issuecomment-286729044)
