### ISSUE TITLE
TSLint has been deprecated

### ISSUE THREAD

**Issue by cseas** [crazyfactory/ts-react-boilerplate#346]
**Is your feature request related to a problem? Please describe.**
The npm package `tslint` has been deprecated in favour of `eslint`.
Reference: https://www.npmjs.com/package/tslint

**Describe the solution you'd like**
Should the tslint package be replaced with `typescript-eslint` in this project?

**Comment by paibamboo** [comment]
Hi @cseas , we've migrated to typescript-eslint for a while. At that time, the typescript-eslint team left option to use old tslint rules because not all tslint rules were migrated to typescript-eslint rules yet. Not sure what the current situation is. You can check it out at https://github.com/crazyfactory/ts-react-boilerplate/blob/master/.eslintrc.js. Old tslint rules are declared by `const tslintRules`, and typescript-eslint rules are prefixed by `@typescript-eslint/`, the rest is eslint rules.

**Comment by cseas** [comment]
Found it. Thanks!
